"""Add converter table

Revision ID: 2d97f4d924db
Revises: 7e2387bc27d5
Create Date: 2021-05-22 17:29:55.145583

"""
from alembic import op
import sqlalchemy as sa

import db


# revision identifiers, used by Alembic.
revision = '2d97f4d924db'
down_revision = '7e2387bc27d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('converters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_to_converter',
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('converter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['converter_id'], ['converters.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_to_converter')
    op.drop_table('converters')
    # ### end Alembic commands ###
